// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories.Concrete.Context;

#nullable disable

namespace Repositories.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.Models.About", b =>
                {
                    b.Property<int>("AboutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AboutId"), 1L, 1);

                    b.Property<string>("AboutDetails")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AboutImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AboutId");

                    b.ToTable("Abouts");
                });

            modelBuilder.Entity("Entities.Models.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandId"), 1L, 1);

                    b.Property<string>("BrandImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrandId");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("Entities.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("CategoryImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CategoryStatus")
                        .HasColumnType("bit");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryImage = "aaaa",
                            CategoryName = "Laptop",
                            CategoryStatus = true
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryImage = "aa",
                            CategoryName = "Akıllı Saat",
                            CategoryStatus = true
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryImage = "aa",
                            CategoryName = "Test Kitapları",
                            CategoryStatus = true
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryImage = "https://technext.github.io/cozastore/images/banner-01.jpg",
                            CategoryName = "Kadın",
                            CategoryStatus = true
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryImage = "https://technext.github.io/cozastore/images/banner-02.jpg",
                            CategoryName = "Erkek",
                            CategoryStatus = true
                        });
                });

            modelBuilder.Entity("Entities.Models.Color", b =>
                {
                    b.Property<int>("ColorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ColorId"), 1L, 1);

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ColorId");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            ColorId = 1,
                            ColorName = "Mavi"
                        },
                        new
                        {
                            ColorId = 2,
                            ColorName = "Sarı"
                        },
                        new
                        {
                            ColorId = 3,
                            ColorName = "Kırmızı"
                        },
                        new
                        {
                            ColorId = 4,
                            ColorName = "Turuncu"
                        },
                        new
                        {
                            ColorId = 5,
                            ColorName = "Siyah"
                        },
                        new
                        {
                            ColorId = 6,
                            ColorName = "Beyaz"
                        },
                        new
                        {
                            ColorId = 7,
                            ColorName = "Gri"
                        });
                });

            modelBuilder.Entity("Entities.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"), 1L, 1);

                    b.Property<string>("CommentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CommentStatus")
                        .HasColumnType("bit");

                    b.Property<string>("CommentSubject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("CommentId");

                    b.HasIndex("ProductId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            CommentId = 1,
                            CommentName = "Test",
                            CommentStatus = true,
                            CommentSubject = "",
                            Message = "ehddhdhscb"
                        },
                        new
                        {
                            CommentId = 2,
                            CommentName = "Test",
                            CommentStatus = true,
                            CommentSubject = "",
                            Message = "ehddhdhscb"
                        },
                        new
                        {
                            CommentId = 3,
                            CommentName = "Test",
                            CommentStatus = true,
                            CommentSubject = "",
                            Message = "ehddhdhscb"
                        });
                });

            modelBuilder.Entity("Entities.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"), 1L, 1);

                    b.Property<string>("ContactMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactSubject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            ContactMail = "yakup.0950@gmail.com",
                            ContactMessage = "test mesajıdır",
                            ContactName = "Yakup",
                            ContactSubject = "Deneme"
                        });
                });

            modelBuilder.Entity("Entities.Models.Gender", b =>
                {
                    b.Property<int>("GenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenderId"), 1L, 1);

                    b.Property<string>("GenderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenderId");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            GenderId = 1,
                            GenderName = "Erkek"
                        },
                        new
                        {
                            GenderId = 2,
                            GenderName = "Kadın"
                        });
                });

            modelBuilder.Entity("Entities.Models.Number", b =>
                {
                    b.Property<int>("NumberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NumberId"), 1L, 1);

                    b.Property<int>("ShoesNumber")
                        .HasColumnType("int");

                    b.HasKey("NumberId");

                    b.ToTable("Numbers");

                    b.HasData(
                        new
                        {
                            NumberId = 1,
                            ShoesNumber = 32
                        },
                        new
                        {
                            NumberId = 2,
                            ShoesNumber = 33
                        },
                        new
                        {
                            NumberId = 3,
                            ShoesNumber = 34
                        },
                        new
                        {
                            NumberId = 4,
                            ShoesNumber = 35
                        },
                        new
                        {
                            NumberId = 5,
                            ShoesNumber = 36
                        },
                        new
                        {
                            NumberId = 6,
                            ShoesNumber = 37
                        },
                        new
                        {
                            NumberId = 7,
                            ShoesNumber = 38
                        },
                        new
                        {
                            NumberId = 8,
                            ShoesNumber = 39
                        },
                        new
                        {
                            NumberId = 9,
                            ShoesNumber = 40
                        },
                        new
                        {
                            NumberId = 10,
                            ShoesNumber = 41
                        },
                        new
                        {
                            NumberId = 11,
                            ShoesNumber = 42
                        },
                        new
                        {
                            NumberId = 12,
                            ShoesNumber = 43
                        },
                        new
                        {
                            NumberId = 13,
                            ShoesNumber = 44
                        },
                        new
                        {
                            NumberId = 14,
                            ShoesNumber = 45
                        },
                        new
                        {
                            NumberId = 15,
                            ShoesNumber = 46
                        });
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ProductDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ProductImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ProductPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(100);

                    b.Property<bool>("ProductStatus")
                        .HasColumnType("bit");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ProductDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductImage = "dddddd",
                            ProductName = "Tişört",
                            ProductPrice = 150,
                            ProductStatus = false
                        },
                        new
                        {
                            ProductId = 2,
                            ProductDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductImage = "dddddd",
                            ProductName = "Pantolon",
                            ProductPrice = 350,
                            ProductStatus = false
                        },
                        new
                        {
                            ProductId = 3,
                            ProductDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductImage = "dddddd",
                            ProductName = "Hırka",
                            ProductPrice = 200,
                            ProductStatus = false
                        });
                });

            modelBuilder.Entity("Entities.Models.ProductComment", b =>
                {
                    b.Property<int>("ProductCommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductCommentId"), 1L, 1);

                    b.Property<int?>("CommentId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("ProductCommentId");

                    b.HasIndex("CommentId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductComments");
                });

            modelBuilder.Entity("Entities.Models.ProductDetailHeadPhone", b =>
                {
                    b.Property<int>("HeadPhoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HeadPhoneId"), 1L, 1);

                    b.Property<string>("BluetoothVersiyon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("CiftTelefonDestegi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ColorId")
                        .HasColumnType("int");

                    b.Property<string>("GurultuOnleme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullanimTipi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuyaTereDayanikli")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HeadPhoneId");

                    b.HasIndex("BrandId");

                    b.HasIndex("ColorId");

                    b.ToTable("ProductDetailHeadPhones");
                });

            modelBuilder.Entity("Entities.Models.ProductDetailManWomen", b =>
                {
                    b.Property<int>("ManWomenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManWomenId"), 1L, 1);

                    b.Property<string>("AyakkabiTipi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ColorId")
                        .HasColumnType("int");

                    b.Property<string>("Image1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Malzeme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberId")
                        .HasColumnType("int");

                    b.Property<int?>("SizeId")
                        .HasColumnType("int");

                    b.Property<string>("Tipi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YakaStili")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ManWomenId");

                    b.HasIndex("BrandId");

                    b.HasIndex("ColorId");

                    b.HasIndex("NumberId");

                    b.HasIndex("SizeId");

                    b.ToTable("ProductDetailManWomens");
                });

            modelBuilder.Entity("Entities.Models.ProductDetailPc", b =>
                {
                    b.Property<int>("PcId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PcId"), 1L, 1);

                    b.Property<string>("BellekHizi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("CihazAgirligi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ColorId")
                        .HasColumnType("int");

                    b.Property<string>("EkranBoyutu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EkranCozunurlugu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EkranYenilemeHizi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RamTipi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDDKapasite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("İslemciNesli")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("İslemciTipi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PcId");

                    b.HasIndex("BrandId");

                    b.HasIndex("ColorId");

                    b.ToTable("ProductDetailPcs");
                });

            modelBuilder.Entity("Entities.Models.ProductDetailPhone", b =>
                {
                    b.Property<int>("PhoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhoneId"), 1L, 1);

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<int?>("ColorId")
                        .HasColumnType("int");

                    b.Property<string>("Image1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bluetooth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cifthat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dahilihafiza")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kameracözünürlügü")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("parmakizi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pilgücü")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("yüztanıma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PhoneId");

                    b.HasIndex("BrandId");

                    b.HasIndex("ColorId");

                    b.ToTable("ProductDetailPhones");
                });

            modelBuilder.Entity("Entities.Models.ProductDetails", b =>
                {
                    b.Property<int>("ProductDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductDetailsId"), 1L, 1);

                    b.Property<int?>("HeadPhoneId")
                        .HasColumnType("int");

                    b.Property<int?>("ManWomenId")
                        .HasColumnType("int");

                    b.Property<int?>("PcId")
                        .HasColumnType("int");

                    b.Property<int?>("PhoneId")
                        .HasColumnType("int");

                    b.Property<string>("ProductExplanation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("TvId")
                        .HasColumnType("int");

                    b.Property<int?>("WacthId")
                        .HasColumnType("int");

                    b.HasKey("ProductDetailsId");

                    b.HasIndex("HeadPhoneId");

                    b.HasIndex("ManWomenId");

                    b.HasIndex("PcId");

                    b.HasIndex("PhoneId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.HasIndex("TvId");

                    b.HasIndex("WacthId");

                    b.ToTable("ProductDetails");
                });

            modelBuilder.Entity("Entities.Models.ProductDetailTv", b =>
                {
                    b.Property<int>("TvId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TvId"), 1L, 1);

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("DahiliUyduAlici")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EkranEbati")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EkranFormati")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HdmiGirisleri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kurulum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PcBaglantisi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wifi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TvId");

                    b.HasIndex("BrandId");

                    b.ToTable("ProductDetailTvs");
                });

            modelBuilder.Entity("Entities.Models.ProductDetailWatch", b =>
                {
                    b.Property<int>("WatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WatchId"), 1L, 1);

                    b.Property<string>("AdımSayar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<int?>("ColorId")
                        .HasColumnType("int");

                    b.Property<string>("GPS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KalpRitmiOlcme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kamera")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SesliGorusme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuGecirme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UykuTakibi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UyumluMarka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WatchId");

                    b.HasIndex("BrandId");

                    b.HasIndex("ColorId");

                    b.ToTable("ProductDetailWatches");
                });

            modelBuilder.Entity("Entities.Models.Size", b =>
                {
                    b.Property<int>("SizeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SizeId"), 1L, 1);

                    b.Property<string>("SizeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SizeId");

                    b.ToTable("Sizes");

                    b.HasData(
                        new
                        {
                            SizeId = 1,
                            SizeName = "S"
                        },
                        new
                        {
                            SizeId = 2,
                            SizeName = "M"
                        },
                        new
                        {
                            SizeId = 3,
                            SizeName = "L"
                        },
                        new
                        {
                            SizeId = 4,
                            SizeName = "XL"
                        },
                        new
                        {
                            SizeId = 5,
                            SizeName = "XXL"
                        },
                        new
                        {
                            SizeId = 6,
                            SizeName = "XXXL"
                        });
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("GenderId")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserFirsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("GenderId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "6b90b93e-a34e-461d-bcb7-a7dc3257e2e6",
                            ConcurrencyStamp = "3db35acb-5227-4f9f-8e71-08821824b84d",
                            Name = "MANAGER",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = "000f7cc3-19d2-46e1-a896-de8421ab46e7",
                            ConcurrencyStamp = "3addd4eb-a080-4a66-983f-c1b110f58597",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Comment", b =>
                {
                    b.HasOne("Entities.Models.Product", "Product")
                        .WithMany("Comments")
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.HasOne("Entities.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Entities.Models.ProductComment", b =>
                {
                    b.HasOne("Entities.Models.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId");

                    b.HasOne("Entities.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Comment");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Entities.Models.ProductDetailHeadPhone", b =>
                {
                    b.HasOne("Entities.Models.Brand", "Brand")
                        .WithMany("ProductDetailHeadPhones")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Entities.Models.Color", "Color")
                        .WithMany("ProductDetailHeadPhones")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Brand");

                    b.Navigation("Color");
                });

            modelBuilder.Entity("Entities.Models.ProductDetailManWomen", b =>
                {
                    b.HasOne("Entities.Models.Brand", "Brand")
                        .WithMany("ProductDetailManWomens")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Entities.Models.Color", "Color")
                        .WithMany("ProductDetailManWomens")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Entities.Models.Number", "Number")
                        .WithMany("ProductDetailManWomens")
                        .HasForeignKey("NumberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Entities.Models.Size", "Size")
                        .WithMany("ProductDetailManWomens")
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Brand");

                    b.Navigation("Color");

                    b.Navigation("Number");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("Entities.Models.ProductDetailPc", b =>
                {
                    b.HasOne("Entities.Models.Brand", "Brand")
                        .WithMany("ProductDetailPcs")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Entities.Models.Color", "Color")
                        .WithMany("ProductDetailPcs")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Brand");

                    b.Navigation("Color");
                });

            modelBuilder.Entity("Entities.Models.ProductDetailPhone", b =>
                {
                    b.HasOne("Entities.Models.Brand", "Brand")
                        .WithMany("ProductDetailPhones")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Entities.Models.Color", "Color")
                        .WithMany("ProductDetailPhones")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Brand");

                    b.Navigation("Color");
                });

            modelBuilder.Entity("Entities.Models.ProductDetails", b =>
                {
                    b.HasOne("Entities.Models.ProductDetailHeadPhone", "HeadPhone")
                        .WithMany("ProductDetails")
                        .HasForeignKey("HeadPhoneId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Entities.Models.ProductDetailManWomen", "ManWomen")
                        .WithMany("ProductDetails")
                        .HasForeignKey("ManWomenId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Entities.Models.ProductDetailPc", "Pc")
                        .WithMany("ProductDetails")
                        .HasForeignKey("PcId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Entities.Models.ProductDetailPhone", "Phone")
                        .WithMany("ProductDetails")
                        .HasForeignKey("PhoneId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Entities.Models.Product", "Product")
                        .WithOne("ProductDetails")
                        .HasForeignKey("Entities.Models.ProductDetails", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.ProductDetailTv", "Tv")
                        .WithMany("ProductDetails")
                        .HasForeignKey("TvId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Entities.Models.ProductDetailWatch", "Watch")
                        .WithMany("ProductDetails")
                        .HasForeignKey("WacthId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("HeadPhone");

                    b.Navigation("ManWomen");

                    b.Navigation("Pc");

                    b.Navigation("Phone");

                    b.Navigation("Product");

                    b.Navigation("Tv");

                    b.Navigation("Watch");
                });

            modelBuilder.Entity("Entities.Models.ProductDetailTv", b =>
                {
                    b.HasOne("Entities.Models.Brand", "Brand")
                        .WithMany("ProductDetailTvs")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("Entities.Models.ProductDetailWatch", b =>
                {
                    b.HasOne("Entities.Models.Brand", "Brand")
                        .WithMany("ProductDetailWatches")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Entities.Models.Color", "Color")
                        .WithMany("ProductDetailWatches")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Brand");

                    b.Navigation("Color");
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.HasOne("Entities.Models.Gender", null)
                        .WithMany("Users")
                        .HasForeignKey("GenderId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.Brand", b =>
                {
                    b.Navigation("ProductDetailHeadPhones");

                    b.Navigation("ProductDetailManWomens");

                    b.Navigation("ProductDetailPcs");

                    b.Navigation("ProductDetailPhones");

                    b.Navigation("ProductDetailTvs");

                    b.Navigation("ProductDetailWatches");
                });

            modelBuilder.Entity("Entities.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Entities.Models.Color", b =>
                {
                    b.Navigation("ProductDetailHeadPhones");

                    b.Navigation("ProductDetailManWomens");

                    b.Navigation("ProductDetailPcs");

                    b.Navigation("ProductDetailPhones");

                    b.Navigation("ProductDetailWatches");
                });

            modelBuilder.Entity("Entities.Models.Gender", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Entities.Models.Number", b =>
                {
                    b.Navigation("ProductDetailManWomens");
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("ProductDetails")
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.ProductDetailHeadPhone", b =>
                {
                    b.Navigation("ProductDetails");
                });

            modelBuilder.Entity("Entities.Models.ProductDetailManWomen", b =>
                {
                    b.Navigation("ProductDetails");
                });

            modelBuilder.Entity("Entities.Models.ProductDetailPc", b =>
                {
                    b.Navigation("ProductDetails");
                });

            modelBuilder.Entity("Entities.Models.ProductDetailPhone", b =>
                {
                    b.Navigation("ProductDetails");
                });

            modelBuilder.Entity("Entities.Models.ProductDetailTv", b =>
                {
                    b.Navigation("ProductDetails");
                });

            modelBuilder.Entity("Entities.Models.ProductDetailWatch", b =>
                {
                    b.Navigation("ProductDetails");
                });

            modelBuilder.Entity("Entities.Models.Size", b =>
                {
                    b.Navigation("ProductDetailManWomens");
                });
#pragma warning restore 612, 618
        }
    }
}
